image:
  file: Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
vscode:
  extensions:
    - edukera.archetype@0.35.0:BwtJ6rwGmyJfrcEVrjJcIA==
tasks:
  - openMode: split-right
    command: |-
      clear && echo '
      Welcome to Gitpod!

      If you haven'\''t forked Babel yet and you want to prepare a PR, you can use
      the Ctrl+P (or ⌘P) shortcut, type `>Fork` and press ENTER: Gitpod\ will
      create the fork for you.

      <-- The other terminal is building Babel. It should automatically rebuild
          when you change a file, so you don'\''t need to worry about it.
          If it'\''s still building, please wait until it'\''s finished!

      If you want to run the tests, you can run `yarn jest` in this terminal,
      or filter by package name (for example, `yarn jest babel-parser`).
      '
