image:
  file: Dockerfile
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
vscode:
  extensions:
    - edukera.archetype
    - baking-bad.michelson@0.1.0
tasks:
  - openMode: tab-after
    command: |-
      npm i @completium/completium-cli@latest -g && completium-cli init && completium-cli install bin archetype && completium-cli import faucet /home/gitpod/admin.json as admin && completium-cli set account admin && sudo ln -s /home/gitpod/.completium/bin/archetype /usr/local/bin/ && clear && echo '
      Welcome to Try archetype!

      Type in this terminal below:

      sh start.sh








      '
